language: php

# use the new container infrastructure
#sudo: false

php:
  - '7.1'

cache:
    directories:
        - vendor

before_script:
  - composer self-update

script:
    - ./vendor/bin/phpspec run
    - ./vendor/bin/phpstan analyse src -l 5
