language: php

# use the new container infrastructure
#sudo: false

php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --dev

script:
    - ./vendor/bin/phpspec run
    - ./vendor/bin/phpstan analyse src -l 5
