version: 2.1

jobs:
    build:
        docker:
            - image: circleci/php:8.0.7-cli
        steps:
            - checkout
            - run: composer install --dev
            - run: ./vendor/bin/phpspec run
            - run: ./vendor/bin/phpstan analyse src -l 5

